/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c04.detalles;

import com.mycompany.c03.adaptadores.ControladorComparador;
import com.mycompany.c02.casosdeuso.CasoDeUsoAdaptador;
import com.mycompany.c02.casosdeuso.PeticionMember;
import com.mycompany.c02.casosdeuso.Transferencia;

import com.mycompany.c03.adaptadores.PresentadorAdaptador;
import com.mycompany.c03.adaptadores.ControladorAdaptador;
import com.mycompany.c03.adaptadores.Vista;
import java.awt.EventQueue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author ELIALVA
 */
@Component
public class AdaptadorIUGrafica extends javax.swing.JFrame implements Vista {

    @Autowired
    CasoDeUsoAdaptador casoDeUsoAdaptador;

    @Autowired
    PresentadorAdaptador presentador;

    ControladorAdaptador controladorAdaptador;
    ControladorComparador controladorComparador;

    /**
     * Creates new form NewJFrame
     */
    public AdaptadorIUGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        PeticionMember peticionOrigen = new PeticionMember();
        peticionOrigen.setServidor("INFOPRO");
        peticionOrigen.setBiblioteca("PNCQP.BTCH.PROCLIB");
        peticionOrigen.setNombre("QAD2700");
        
        PeticionMember peticionDestino = new PeticionMember();
        peticionDestino.setServidor("INFODES");
        peticionDestino.setBiblioteca("TN6EAM.BTCH.PROCLIB");
        peticionDestino.setNombre("QAD2700");        
        
        Transferencia transferencia = new Transferencia();
        transferencia.setOrigen(peticionOrigen);
        transferencia.setDestino(peticionDestino);
        transferencia.setTipo("PROC");
        
        controladorAdaptador.resuelve(Arrays.asList(transferencia));
        
        JOptionPane.showConfirmDialog(this, "hola");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    public void inicia() {
        EventQueue.invokeLater(() -> {
            AdaptadorIUGrafica.this.setVisible(true);
        });
        
        

        controladorAdaptador = new ControladorAdaptador(casoDeUsoAdaptador, presentador, this);
        
    }
}
