/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.c04.detalles;

import com.mycompany.c01.entidades.Member;
import com.mycompany.c02.casosdeuso.ComparaMembersCasoDeUso;
import com.mycompany.c03.adaptadores.ComparaMembersControlador;
import com.mycompany.c02.casosdeuso.AdaptaMembersCasoDeUso;
import com.mycompany.c02.casosdeuso.Transferencia;
import com.mycompany.c03.adaptadores.ComparaMembersPresentador;

import com.mycompany.c03.adaptadores.AdaptaMembersPresentador;
import com.mycompany.c03.adaptadores.AdaptaMembersControlador;
import com.mycompany.c03.adaptadores.AdaptaMembersModeloVista;
import com.mycompany.c03.adaptadores.ComparaMembersModeloVista;
import com.mycompany.c03.adaptadores.Vista;
import java.awt.EventQueue;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 *
 * @author ELIALVA
 */
@Component
public class AdaptadorIUGraficaTest extends javax.swing.JFrame implements Vista {

    /**
     * Creates new form NewJFrame
     */
    public AdaptadorIUGraficaTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        Member peticionOrigen = new Member();
        peticionOrigen.setServidor("INFOPRO");
        peticionOrigen.setBiblioteca("PNCQP.BTCH.PROCLIB");
        peticionOrigen.setNombre("QAD2700");
        
        Member peticionDestino = new Member();
        peticionDestino.setServidor("INFODES");
        peticionDestino.setBiblioteca("TN6EAM.BTCH.PROCLIB");
        peticionDestino.setNombre("QAD2700");
        
        Transferencia transferencia = new Transferencia();
        transferencia.setOrigen(peticionOrigen);
        transferencia.setDestino(peticionDestino);
        transferencia.setTipo("PROC");
        
        adaptaMembersControlador.resuelve(Arrays.asList(transferencia));
        
        JOptionPane.showConfirmDialog(this, "hola");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:        
        Member peticionOrigen = new Member();
        peticionOrigen.setServidor("INFOPRO");
        peticionOrigen.setBiblioteca("PNCQP.BTCH.PROCLIB");
        peticionOrigen.setNombre("QAD2700");
        
        Member peticionDestino = new Member();
        peticionDestino.setServidor("INFODES");
        peticionDestino.setBiblioteca("TN6EAM.BTCH.PROCLIB");
        peticionDestino.setNombre("QAD2700");
        
        Transferencia transferencia = new Transferencia();
        transferencia.setOrigen(peticionOrigen);
        transferencia.setDestino(peticionDestino);
        transferencia.setTipo("PROC");
        
        comparaMembersControlador.compara(transferencia);
        
        JOptionPane.showConfirmDialog(this, "hola");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

    public void inicia() {
        EventQueue.invokeLater(() -> {
            AdaptadorIUGraficaTest.this.setVisible(true);
        });
        
        adaptaMembersControlador = new AdaptaMembersControlador(adaptaMembersCasoDeUso, adaptaMembersPresentador, this);
        comparaMembersControlador = new ComparaMembersControlador(comparaMembersCasoDeUso, comparaMembersPresentador, this);
        
    }
    
    @Autowired
    AdaptaMembersCasoDeUso adaptaMembersCasoDeUso;
    @Autowired
    AdaptaMembersPresentador adaptaMembersPresentador;
    AdaptaMembersControlador adaptaMembersControlador;
    
    @Autowired
    ComparaMembersCasoDeUso comparaMembersCasoDeUso;
    @Autowired
    ComparaMembersPresentador comparaMembersPresentador;
    ComparaMembersControlador comparaMembersControlador;
    
    ComparaMembersControlador controladorComparador;
    
    @Override
    public void muestra(AdaptaMembersModeloVista modeloVista) {
        
        Map<String, List<String>> bitacora = modeloVista.getBitacora();
        bitacora.forEach((origen, texto) -> {
            System.out.println("En view-------");
            System.out.println("llave " + origen);
            System.out.println("texto " + texto);
        });        
    }
    
    @Override
    public void muestra(ComparaMembersModeloVista modeloVista) {
        try {
            this.setVisible(false);
            System.out.println("modele");
            File destino = modeloVista.getDestino();
            File origen = modeloVista.getOrigen();
            Process process = new ProcessBuilder(
                    "D:\\Users\\ELIALVA\\Desktop\\GNP Custmizador\\workbench\\WinMerge\\WinMergeU.exe", "/e", "/wl", "/wr", origen.getAbsolutePath(), destino.getAbsolutePath())
                    .start();
            while (process.isAlive()) {                
            }
            this.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(AdaptadorIUGraficaTest.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
}
